name: Build XNU Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-xnu:
    runs-on: macos-14

    env:
      RC_DARWIN_KERNEL_VERSION: 26
      BUILD_LTO: 0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set KDK_PATH and SDKROOT
        run: |
          export KDK_PATH=/Library/Developer/KDKs/KDK_26.1_25B5042k.kdk
          export SDKROOT="$KDK_PATH/SDKs/MacOSX.sdk"
          echo "KDK_PATH=$KDK_PATH"
          echo "SDKROOT=$SDKROOT"

      - name: Prepare build log
        run: echo "Build start $(date)" > build.log

      - name: Verify availability.pl
        run: |
          SDKROOT=/Library/Developer/KDKs/KDK_26.1_25B5042k.kdk/SDKs/MacOSX.sdk
          if [ ! -x "$SDKROOT/usr/local/libexec/availability.pl" ]; then
            echo "Error: availability.pl missing or not executable"
            exit 1
          fi

      - name: Build XNU Kernel
        run: |
          export KDK_PATH=/Library/Developer/KDKs/KDK_26.1_25B5042k.kdk
          export SDKROOT="$KDK_PATH/SDKs/MacOSX.sdk"
          cd xnu
          make ARCH_CONFIGS=X86_64 KERNEL_CONFIGS=RELEASE \
               SDKROOT="$SDKROOT" BUILD_LTO="$BUILD_LTO" \
               -j$(sysctl -n hw.ncpu) 2>&1 | tee -a ../build.log
          exitcode=${PIPESTATUS[0]}
          if [ "$exitcode" -ne 0 ]; then
            echo "::error::make failed with exit $exitcode"
            exit "$exitcode"
          fi

      - name: Upload build log
        uses: actions/upload-artifact@v3
        with:
          name: xnu-build-log
          path: build.log